"use client"; // Generated by Copilot

import React, { useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { usePathname } from "next/navigation"; // Generated by Copilot

// Generated by Copilot
import { useTransitionContext } from "../../lib/transition-context";

interface PageTransitionProps {
  children: React.ReactNode;
}

// Animation variants for page transitions
const pageVariants = {
  initial: {
    opacity: 0,
    scale: 0.98,
  },
  in: {
    opacity: 1,
    scale: 1,
  },
  out: {
    opacity: 0,
    scale: 1.02,
  },
};

const pageTransition = {
  type: "tween" as const,
  ease: "anticipate" as const,
  duration: 0.5,
};

const PageTransition: React.FC<PageTransitionProps> = ({ children }) => {
  const pathname = usePathname(); // Generated by Copilot
  const {
    _isAnimating: isAnimating,
    _setIsAnimating: setIsAnimating,
    _previousPath: previousPath,
    _setPreviousPath: setPreviousPath,
    _exitAnimation: exitAnimation,
    _setExitAnimation: setExitAnimation,
  } = useTransitionContext();

  useEffect(() => {
    // When the pathname changes, update the previous path
    // and set isAnimating to false (animation complete)
    if (previousPath !== pathname && isAnimating) {
      setTimeout(() => {
        setIsAnimating(false);
        setExitAnimation(false);
      }, 600); // Slightly longer than the animation duration to ensure completion
    }

    // Add null check before setting the previous path
    if (pathname !== null) {
      setPreviousPath(pathname);
    }
  }, [
    pathname,
    previousPath,
    isAnimating,
    setIsAnimating,
    setPreviousPath,
    setExitAnimation,
  ]);

  // If exitAnimation is true, it means a link was clicked and we should animate out
  useEffect(() => {
    if (exitAnimation) {
      setIsAnimating(true);
    }
  }, [exitAnimation, setIsAnimating]);

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={pathname}
        initial="initial"
        animate="in"
        exit="out"
        variants={pageVariants}
        transition={pageTransition}
        className="w-full h-full"
      >
        {children}
      </motion.div>
    </AnimatePresence>
  );
};

export default PageTransition;
