"use client";

import React, { useState } from "react";
import { Menu, X, Calendar } from "lucide-react";
import { useIsMobile } from "@/hooks/use-mobile"; // Generated by Copilot
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { usePathname } from "next/navigation";
import { useToast } from "@/hooks/use-toast"; // Generated by Copilot

const Header = () => {
  const isMobile = useIsMobile();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const { toast } = useToast();

  const toggleMobileMenu = () => {
    setMobileMenuOpen(!mobileMenuOpen);
  };

  const handleScrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    if (element) {
      // Close mobile menu if open
      if (mobileMenuOpen) {
        setMobileMenuOpen(false);
      }

      // Add a small delay to ensure mobile menu closing animation completes
      setTimeout(
        () => {
          // Get header height to offset scroll position
          const headerHeight =
            document.querySelector("header")?.offsetHeight || 0;

          // Calculate position to scroll to
          const elementPosition = element.getBoundingClientRect().top;
          const offsetPosition =
            elementPosition + window.pageYOffset - headerHeight - 20;

          // Smooth scroll to element
          window.scrollTo({
            top: offsetPosition,
            behavior: "smooth",
          });
        },
        mobileMenuOpen ? 300 : 0
      );
    }
  };

  const handleBookTasting = () => {
    toast({
      title: "Booking Request Received",
      description:
        "Thank you for your interest! A representative will contact you shortly to confirm your tasting.",
    });
  };

  const NavLink = ({
    sectionId,
    children,
  }: {
    sectionId: string;
    children: React.ReactNode;
  }) => (
    <button
      className="text-deep-brown- hover:text-wineRed-100 transition-colors cursor-pointer text-left"
      onClick={() => handleScrollToSection(sectionId)}
    >
      {children}
    </button>
  );

  return (
    <header className="fixed top-0 left-0 right-0 z-50 bg-white-100/90 backdrop-blur-sm shadow-sm">
      <div className="container mx-auto flex justify-between items-center py-4 px-4 md:px-6">
        <motion.div
          className="flex items-center"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5 }}
        >
          <button
            className="text-2xl font-serif text-gold-100 font-bold cursor-pointer"
            onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          >
            Kalchev Family Winery
          </button>
        </motion.div>

        {/* Desktop Navigation */}
        {!isMobile && (
          <motion.nav
            className="hidden md:flex space-x-6"
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{
              duration: 0.5,
              staggerChildren: 0.1,
              delayChildren: 0.2,
            }}
          >
            <NavLink sectionId="about">About</NavLink>
            <NavLink sectionId="wines">Our Wines</NavLink>
            <NavLink sectionId="experience">Experience</NavLink>
            <NavLink sectionId="testimonials">Testimonials</NavLink>
            <NavLink sectionId="wine-club">Wine Club</NavLink>
            <NavLink sectionId="contact">Contact</NavLink>
          </motion.nav>
        )}

        {/* CTA Button */}
        <motion.div
          className="hidden md:block"
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          <Button
            variant="default"
            size="sm"
            className="bg-gold-100 text-white-100 hover:bg-wineRed-100 transition-colors duration-300"
            onClick={handleBookTasting}
          >
            <Calendar className="h-4 w-4 mr-2" />
            Book Tasting
          </Button>
        </motion.div>
      </div>
    </header>
  );
};

export default Header;
