"use client";
import React from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";

const Hero = () => {
  return (
    <div className="relative h-screen w-full flex items-center justify-center text-white-100"> {/* Generated by Copilot */}
      <Image
        src="/images/hero-bg.jpg"
        alt="Hero Image"
        fill={true} // Generated by Copilot
        style={{ objectFit: "cover" }} // Generated by Copilot
        className="absolute inset-0 opacity-20"
        sizes="100vw" // Generated by Copilot
        priority
      />
      <div className="bg-img-overlay"></div>
      <div className="flex flex-col max-w-4xl text-center justify-center items-center mx-auto px-1 py-24 z-10">
        <small>Welcome to Kalchev Family Winery</small>
        <h1 className="text-6xl font-bold font-playfair text-gold-200 mb-4">
          Crafting Exceptional Wine Since 1932
        </h1>
        <p className="text-xl max-w-3xl">
          Experience the essence of Macedonia wine tradition with our artisanal,
          family-crafted wines from the heart of the Bogdanci Valley.
        </p>
        <div className="space-x-4">
          <Button
            variant="default"
            className="mt-4 bg-gold-100 text-white-100 hover:bg-wineRed-100 
        transition-colors duration-300"
          >
            Learn More
          </Button>
          <Button
            variant="outline"
            className="mt-4 bg-transparent text-white-100 hover:bg-wineRed-100
        transition-colors duration-300"
          >
            Book Tasting
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Hero;
