"use client"; // Generated by Copilot

import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import { TransitionProvider } from "@/lib/transition-context";
import { StyleRegistry } from "@/lib/style-registry";
import { CartProvider } from "@/lib/cart-context";
import CartDrawer from "@/components/cart/CartDrawer";
import ScrollToTop from "@/components/layout/ScrollToTop";
import { LocaleProvider } from "@/lib/i18n/locale-context";
import type { Locale } from "@/lib/i18n/translations";

interface ClientLayoutProps {
  children: ReactNode;
  initialLocale?: Locale;
}

// Generated by Copilot
export function ClientLayout({ children, initialLocale }: ClientLayoutProps) {
  return (
    <StyleRegistry>
      <LocaleProvider initialLocale={initialLocale}>
        <CartProvider>
          <TransitionProvider>
            <main id="main-content" suppressHydrationWarning>
              {children}
            </main>
            <CartDrawer />
            <ScrollToTop />
            <Toaster />
          </TransitionProvider>
        </CartProvider>
      </LocaleProvider>
    </StyleRegistry>
  );
}
