"use client"; // Generated by Copilot

import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import { TransitionProvider } from "@/lib/transition-context";
import { StyleRegistry } from "@/lib/style-registry";
import { CartProvider } from "@/lib/cart-context";
import CartDrawer from "@/components/cart/CartDrawer";
import { LocaleProvider } from "@/lib/i18n/locale-context";

interface ClientLayoutProps {
  children: ReactNode;
}

// Generated by Copilot
export function ClientLayout({ children }: ClientLayoutProps) {
  return (
    <StyleRegistry>
      <LocaleProvider>
        <CartProvider>
          <TransitionProvider>
            {children}
            <CartDrawer />
            <Toaster />
          </TransitionProvider>
        </CartProvider>
      </LocaleProvider>
    </StyleRegistry>
  );
}
