"use client"; // Generated by Copilot

import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import { TransitionProvider } from "@/lib/transition-context";
import { StyleRegistry } from "@/lib/style-registry";

interface ClientLayoutProps {
  children: ReactNode;
}

// Generated by Copilot
export function ClientLayout({ children }: ClientLayoutProps) {
  return (
    <StyleRegistry>
      <TransitionProvider>
        {children}
        <Toaster />
      </TransitionProvider>
    </StyleRegistry>
  );
}
