import { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { metaData } from "@/config/site";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { TransitionProvider } from "@/lib/transition-context";
import { StyleRegistry } from "@/lib/style-registry"; // Generated by Copilot

const playfairDisplay = localFont({
  src: "./fonts/PlayfairDisplayVF.ttf",
  variable: "--font-playfair-display",
  weight: "100, 200, 300, 400, 500, 600, 700, 800, 900",
});

const inter = localFont({
  src: "./fonts/InterVF.ttf",
  variable: "--font-inter",
  weight: "100, 200, 300, 400, 500, 600, 700, 800, 900",
});

export const metadata: Metadata = {
  title: {
    default: metaData.name,
    template: `%s | ${metaData.name}`,
  },
  description: metaData.description,
  openGraph: {
    type: "website",
    locale: "en_US",
    url: metaData.url,
    title: metaData.title,
    description: metaData.description,
    siteName: metaData.name,
  },
  icons: "/favicon.ico",
};

import { ClientLayout } from "./client-layout";

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${playfairDisplay.variable} ${inter.variable}`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
};

export default RootLayout;
