"use client"; // Generated by Copilot

import React, { useEffect } from "react";

// Generated by Copilot
interface StyleRegistryProps {
  children: React.ReactNode;
}

/**
 * A component that ensures proper CSS loading when using Turbopack
 * Helps prevent "No link element found for chunk" errors
 */
export function StyleRegistry({ children }: StyleRegistryProps) {
  useEffect(() => {
    const missingChunks = document.querySelectorAll("link[data-missing-chunk]");

    if (missingChunks.length > 0) {
      console.debug(
        `StyleRegistry: Found ${missingChunks.length} missing CSS chunks, reloading them`,
      );

      missingChunks.forEach((link) => {
        const href = link.getAttribute("href");
        if (href) {
          const newLink = document.createElement("link");
          newLink.rel = "stylesheet";
          newLink.href = href;
          document.head.appendChild(newLink);
        }
      });
    }
  }, []);

  return <>{children}</>;
}
