"use client"; // Generated by Copilot

import React, { useEffect } from "react";

// Generated by Copilot
interface StyleRegistryProps {
  children: React.ReactNode;
}

/**
 * A component that ensures proper CSS loading when using Turbopack
 * Helps prevent "No link element found for chunk" errors
 */
export function StyleRegistry({ children }: StyleRegistryProps) {
  // Track if we're in the browser
  const _isBrowser = typeof window !== "undefined";

  useEffect(() => {
    if (_isBrowser) {
      // Find any missing CSS chunks and ensure they load properly
      const _missingChunks = document.querySelectorAll(
        "link[data-missing-chunk]"
      );

      if (_missingChunks.length > 0) {
        console.debug(
          `StyleRegistry: Found ${_missingChunks.length} missing CSS chunks, reloading them`
        );

        _missingChunks.forEach((link) => {
          const href = link.getAttribute("href");
          if (href) {
            // Force reload the CSS
            const newLink = document.createElement("link");
            newLink.rel = "stylesheet";
            newLink.href = href;
            document.head.appendChild(newLink);
          }
        });
      }
    }
  }, [_isBrowser]);

  return <>{children}</>;
}
