"use client"; // Generated by Copilot

import React, { createContext, useContext, useState } from "react";

type TransitionContextType = {
  _isAnimating: boolean;
  _setIsAnimating: (isAnimating: boolean) => void;
  _previousPath: string;
  _setPreviousPath: (path: string) => void;
  _exitAnimation: boolean;
  _setExitAnimation: (exit: boolean) => void;
};

const TransitionContext = createContext<TransitionContextType | undefined>(undefined);

export const TransitionProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [_isAnimating, _setIsAnimating] = useState(false);
  const [_previousPath, _setPreviousPath] = useState("/");
  const [_exitAnimation, _setExitAnimation] = useState(false);

  return (
    <TransitionContext.Provider
      value={{
        _isAnimating,
        _setIsAnimating,
        _previousPath,
        _setPreviousPath,
        _exitAnimation,
        _setExitAnimation,
      }}
    >
      {children}
    </TransitionContext.Provider>
  );
};

export const useTransitionContext = (): TransitionContextType => {
  const context = useContext(TransitionContext);
  if (context === undefined) {
    throw new Error("useTransitionContext must be used within a TransitionProvider");
  }
  return context;
};
